Fixed workflow file

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,37 +5,38 @@ jobs:
     name: Build and Test
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - uses: haskell/actions/setup@v1
-      with:
-        enable-stack: true
-        ghc-version: 8.6.5
-        cabal-version: 'latest'
-        stack-version: 'latest'
-    - name: Cache Stack
-      uses: actions/cache@v2
-      with:
-        path: | 
-          ~/.stack
-          .stack-work
-        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
-        restore-keys: |
-          ${{ runner.os }}-stack
-    - run: stack build
-    - run: stack test
-  
+      - uses: actions/checkout@v2
+      - uses: haskell/actions/setup@v1
+        with:
+          enable-stack: true
+          ghc-version: 8.6.5
+          cabal-version: "latest"
+          stack-version: "latest"
+      - name: Cache Stack
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/.stack
+            .stack-work
+          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-stack
+      - run: stack build
+      - run: stack test
+
   linting-haskell:
     name: Linting Haskell
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - run: |
-      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
-      curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
-      if [ -z "$(git status --porcelain)" ]; then
-          echo "No style errors detected."
-      else
-          echo "Style errors detected:"
-          git --no-pager diff
-          exit 1
-      fi
+      - uses: actions/checkout@v2
+      - name: Check hlint and stylish
+        run: |
+          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
+          curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
+          if [ -z "$(git status --porcelain)" ]; then
+              echo "No style errors detected."
+          else
+              echo "Style errors detected:"
+              git --no-pager diff
+              exit 1
+          fi
